TrainManagement.Web/Models/ErrorViewModel.cs
namespace TrainManagement.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TrainManagement.Web/Models/TrainModel.cs
using System.ComponentModel.DataAnnotations;
namespace TrainManagement.Web.Models
{
    public class TrainModel
    {
        [Key]
        public int TrainId { get; set; }

        [Required(ErrorMessage = "Please enter departure station")]
        [Display(Name = "Start from")]
        public string? DepartureStation { get; set; }

        [Required(ErrorMessage = "Please enter final destination")]
        [Display(Name = "Final destination")]
        public string? FinalDestination { get; set; }

        //[Required(ErrorMessage = "Please enter train length")]
        [Display(Name = "Train lenght on this direction")]
        [Range(1, 100, ErrorMessage = "Please enter a valid train length (1-100)")]
        public int TrainLength { get; set; }

        [Display(Name = "Including empty carriages")]
        [Range(0, 100, ErrorMessage = "Please enter a valid amount of empty carriages (1-100)")]
        public int EC { get; set; }

        [Display(Name = "Maximum train weight for this direction")]
        public int Weight { get; set; }

        //[Required(ErrorMessage = "Please enter Average Amount Of Carriages Per Day")]
        [Display(Name = "Average amount of carriages per day")]
        public int AverageAmountPerDay { get; set; } 

        [Display(Name = "Amount of carriages with dangerous cargo")]
        public int DC { get; set; } 

    }
}

TrainManagement.Web/Models/UserModel.cs
using System.ComponentModel.DataAnnotations;

namespace TrainManagement.Web.Models
{
    public class UserModel
    {
        [Key]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Please enter your First name")]
        [MinLength(3, ErrorMessage = "First name is too short")]
        [Display(Name = "First name")]
        public string? FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your Last name")]
        [MinLength(3, ErrorMessage = "Last name is too short")]
        [Display(Name = "Last name")]
        public string? LastName { get; set; }
        public string? Password { get; set; }
    }
}

TrainManagement.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TrainManagement.Web.Models;

namespace TrainManagement.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TrainManagement.Web/Controllers/TrainController.cs
using Microsoft.AspNetCore.Mvc;
using TrainManagement.Web.Data;
using TrainManagement.Web.Models;

namespace TrainManagement.Web.Controllers
{
    public class TrainController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TrainController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string SearchString)
        {
            //IEnumerable<TrainModel> trainList = _context.Trains.ToList();
            //return View(trainList);
            ViewData["Filter"] = SearchString;
            var train = from t in _context.Trains select t;
            if (!String.IsNullOrEmpty(SearchString))
            {
                train = train.Where(t => t.FinalDestination.Contains(SearchString) || t.DepartureStation.Contains(SearchString));               
            }           

            return View(train);
        }

        public IActionResult Add(TrainModel trainModel)
        {
            if (ModelState.IsValid)
            {
                _context.Trains.Add(trainModel);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult TrainEdit(int? Id)
        {
            var _trainModel = _context.Trains.Find(Id);
            if (_trainModel == null)
            {
                return NotFound();
            }

            return View(_trainModel);
        }

        [HttpPost]
        public IActionResult Edit(TrainModel trainModel)
        {
            if (ModelState.IsValid)
            {
                _context.Trains.Update(trainModel);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
                
        [HttpPost, ActionName("Delete")]
        public IActionResult Delete(int? Id)
        {
            var _trainModel = _context.Trains.Find(Id);
            if (_trainModel == null)
            {
                return NotFound();
            }
            _context.Trains.Remove(_trainModel);
            _context.SaveChanges();            
            return RedirectToAction("Index");
                        
        }
        public IActionResult TrainCalculate(int? Id)
        {
            var _trainModel = _context.Trains.Find(Id);
            if (_trainModel == null)
            {
                return NotFound();
            }

            return View(_trainModel);
        }
    }
}

TrainManagement.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TrainManagement.Web.Data;
using TrainManagement.Web.Models;

namespace TrainManagement.Web.Controllers
{
    public class UserController : Controller
    {
        public readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Login(string FirstName, string LastName, string Password)
        {
            ViewBag.LoginStatus = "";
            if (ModelState.IsValid)
            {
                var userCheck = _context.Users.FirstOrDefault(u => u.FirstName == FirstName && u.LastName == LastName && u.Password == Password);

                if (userCheck == null)
                {
                    ViewBag.LoginStatus = "User not registered";
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }

        public IActionResult Registration(UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                _context.Users.Add(userModel);
                _context.SaveChanges();
                return RedirectToAction("Login");
            }
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

TrainManagement.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <br/>
    <h1 class="display-4">to the TrainManagement.Web</h1>    
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>

TrainManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainManagement.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrainManagement.Web.styles.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/css/Cosmo.css" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light @*bg-grey*@ border-bottom box-shadow mb-3" style="background-color:lightgray">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h2>TrainManagement.Web</h2></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item" style="margin-left:500px; margin-right:200px; /*text-align:right*/ ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Train" asp-action="Index"><h4>Start</h4></a>
                        </li>
                        <li class="nav-item" style="margin-left:300px; @*text-align:right*@">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login"><h5>Sign In or Sign Up</h5></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="bottom:0;position:fixed;width:100%;text-align:center; background-color:lightgray">
        <div class="container" style="color:black">
            &copy; 2022 - TrainManagement.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TrainManagement.Web/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainManagement.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TrainManagement.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light @*bg-white*@ border-bottom box-shadow mb-3" style="background-color:lightgray">
            <div class="container-fluid">
                <h2>TrainManagement.Web</h2>              
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="bottom:0;position:fixed;width:100%;text-align:center; background-color:lightgray">
        <div class="container" style="color:black">
            &copy; 2022 - TrainManagement.Web - by Projkeen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TrainManagement.Web/Views/Train/Add.cshtml
@model TrainModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["title"] = "Add New Train";
}

<form method="post" asp-action="Add" autocomplete="off">
    <div class="border p-2">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h4 class="text-black pl-3">Add New Train</h4>
        </div>

        <div class="row">
            <div class="col-4">
                <label asp-for="DepartureStation"><b>Departure station</b></label>
                <input asp-for="DepartureStation" class="form-control" />
                <span asp-validation-for="DepartureStation" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="FinalDestination"><b>Final destination</b></label>
                <input asp-for="FinalDestination" class="form-control" />
                <span asp-validation-for="FinalDestination" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="Weight"><b>Maximum train weight on this direction</b></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="TrainLength"><b>Train length on this direction (in railway carriages)</b></label>
                <input asp-for="TrainLength" class="form-control" />
                <span asp-validation-for="TrainLength" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="EC"><b>Including empty railway carriages</b></label>
                <input asp-for="EC" class="form-control" />
                <span asp-validation-for="EC" class="text-danger"></span>
            </div>
        </div>
        <br />
       
        <div class="row">
            <div class="col-4">
                <label asp-for="AverageAmountPerDay"><b>Amount of carriages per day on this destination (in railway carriages)</b></label>
                <input asp-for="AverageAmountPerDay" class="form-control" />
                <span asp-validation-for="AverageAmountPerDay" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="DC"><b>Amount of railway carriages with dangerous cargo</b></label>
                <input asp-for="DC" class="form-control" />
                <span asp-validation-for="DC" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="w-12 btn-group" role="group">
            <a asp-action="Index" class="btn btn-info mx-1">🡸 Back</a>
            <input type="submit" class="btn btn-danger mx-1" value="✓ Add" />
        </div>
    </div>
</form>

TrainManagement.Web/Views/Train/Index.cshtml
@model IEnumerable<TrainModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Listing of All Directions";
}
<div>
    <div class="row pt-4">
        <div class="col-5">
            <h2 class="text" style="margin-left:150px">Directions →</h2>
        </div>
        <div class="col-3">
            <a asp-controller="Train" asp-action="Add" class="btn btn-secondary btn-lg">+ Add New Direction</a>
        </div>
        <div class="col-4">
            <form asp-action="Index" method="get">
                <div class="w-100 btn-group" role="group">                    
                    <input type="text" class="form-control" name="SearchString" placeholder="Search in directions" autocomplete="off" value="@ViewData["Filter"]" />
                    <input type="submit" value="🔍 Search" class="btn btn-secondary" />
                    <a asp-action="Index" class="btn btn-info">🆑Clear</a>
                </div>
            </form>            
        </div>
    </div>
</div>
<br />

@if (Model.Count() > 0)
{
    <table class="table table-bordered table-hover table-striped" style="text-align:center" width="100%">
        <thead>
            <tr>
                <th>Departure Station</th>
                <th>Final Destination</th>
                <th>Train length on this direction (in railway carriages)</th>
                <th>Maximum train weight on this direction</th>
                <th>Average amount of carriages per day on this direction</th>
                <th>Manage</th>
            </tr>
        </thead>
        <tbody style="font-size:larger">
            @foreach (var i in Model)
            {
                <tr>
                    <td width="15%">@i.DepartureStation</td>
                    <td width="15%">@i.FinalDestination</td>
                    <td width="15%">@i.TrainLength</td>
                    <td width="15%">@i.Weight</td>
                    <td width="15%">@i.AverageAmountPerDay</td>
                    <td width="25%">
                        <form asp-action="Delete" asp-route-id="@i.TrainId">
                            <div class="w-100 btn-group" role="group">                               
                                <a asp-controller="Train" asp-action="TrainCalculate" asp-route-id="@i.TrainId" class="btn btn-outline-success">Show details</a>
                                <a asp-controller="Train" asp-action="TrainEdit" asp-route-id="@i.TrainId" class="btn btn-outline-secondary">Edit</a>
                                <button type="submit" class="btn btn-outline-danger" onclick="return confirm('⚠ Are you sure?')">Delete</button>
                            </div>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p class="text-center"><b>No trains</b></p>
}

TrainManagement.Web/Views/Train/TrainCalculate.cshtml
@model TrainModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Calculation Results";
}
@{
    int lc = Model.TrainLength - Model.EC;
    double factWeight = (25.4 * Model.EC + 80 * lc);
    double overWeight = factWeight - Model.Weight;
    int amountOfTrains = Model.AverageAmountPerDay / Model.TrainLength;
    int needRailwayCarriage = Model.TrainLength - (Model.AverageAmountPerDay % Model.TrainLength);
    //var ts = TimeSpan.FromMinutes(Model.TrainLength * 2.4);
    TimeSpan ts = TimeSpan.FromMinutes(Model.TrainLength * 1.7 + Model.DC * 2.3);
    TimeSpan tvs = new TimeSpan(ts.Ticks - (ts.Ticks % 600000000));
    TimeSpan overts = TimeSpan.FromMinutes(Model.AverageAmountPerDay * 1.7 + Model.DC * 2.3);
    var time = tvs * amountOfTrains;


}

<h3 style="text-align:center" class="pt-5">Results calculation the train formation on direction from @Model.DepartureStation to @Model.FinalDestination</h3>
<br />

<table class="table table-bordered table-hover table-striped" style="text-align:center" width="100%">
    <thead style="height:auto; vertical-align: central" width=50%>

    <tbody>
        <tr>
            <th>Train Length(railway carriages)</th>
            <td style="font-size:larger">
                    @if (Model.TrainLength <= Model.AverageAmountPerDay)
                    {
                    <p>@Model.TrainLength </p>
                    }
                    else
                    {
                    <p>@Model.AverageAmountPerDay</p>
                    }
            </td>
        </tr>
        <tr>
            <th>Weight</th>
            <td style="font-size:larger">
                    @if (factWeight <= Model.Weight)
                    {
                    <p> Weight matching and equals @factWeight tons </p>
                    }
                    else
                    {
                    <p>Overweight in @overWeight tons</p>
                    }
            </td>
        </tr>
        <tr>
            <th>Time required to form one train</th>
            <td style="font-size:larger">
                    @if (Model.TrainLength <= Model.AverageAmountPerDay)
                    {
                    <p>@tvs</p>
                    }
                    else
                    {
                    <p>@overts</p>
                    }
                    
            </td>
        </tr>
        <tr>
            <th>Amount carriages with dangerous cargo</th>
            <td style="font-size:larger">@Model.DC</td>
        </tr>
        <tr>
            <th>Amount of trains</th>
            <td style="font-size:larger">
                    @if (Model.TrainLength <= Model.AverageAmountPerDay)
                    {
                    <p>@amountOfTrains</p>
                    }
                    else
                    {
                    <p>1</p>
                    }
            </td>
        </tr>
        <tr>
            <th>Required number of railway carriages for a new train</th>
            <td style="font-size:larger">
                    @if (Model.AverageAmountPerDay <= Model.TrainLength)
                    {
                    <p>needed @needRailwayCarriage for a full train</p>
                    }
                    else
                    {
                    <p>@needRailwayCarriage</p>
                    }
            </td>
        </tr>
        <tr>
            <th>Time required to form all trains for this direction</th>
            <td style="font-size:larger">
                    @if (Model.TrainLength <= Model.AverageAmountPerDay)
                    {
                    <p>@time</p>
                    }
                    else
                    {
                    <p>@overts</p>
                    }
            </td>
        </tr>
    </tbody>
</table>

<div class="w-12 btn-group" role="group">
    <a asp-action="Index" class="btn btn-info mx-1">🡸 Back</a>
    <a asp-controller="Train" asp-action="TrainEdit" asp-route-id="@Model.TrainId" class="btn btn-secondary mx-1">Edit</a>
</div>

TrainManagement.Web/Views/Train/TrainEdit.cshtml
@model TrainModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "View Train Details for Edit";
}

<form method="post" asp-action="Edit">
    <input asp-for="TrainId" hidden />
    <div class="border p-1">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Сhange train data</h2>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="DepartureStation"><b>Start from</b></label>
                <input asp-for="DepartureStation" class="form-control" readonly/>
                <span asp-validation-for="DepartureStation" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="FinalDestination"><b>Final destination</b></label>
                <input asp-for="FinalDestination" class="form-control" readonly/>
                <span asp-validation-for="FinalDestination" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="Weight"><b>Maximum train weight on this direction</b></label>
                <input asp-for="Weight" class="form-control" readonly/>
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="TrainLength"><b>Train length on this direction</b></label>
                <input asp-for="TrainLength" class="form-control" />
                <span asp-validation-for="TrainLength" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="EC"><b>Including empty railway carriages</b></label>
                <input asp-for="EC" class="form-control" />
                <span asp-validation-for="EC" class="text-danger"></span>
            </div>
        </div>
        <br />        
        <div class="row">
            <div class="col-4">
                <label asp-for="AverageAmountPerDay"><b>Amount of carriages per day</b></label>
                <input asp-for="AverageAmountPerDay" class="form-control" />
                <span asp-validation-for="AverageAmountPerDay" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-4">
                <label asp-for="DC"><b>Amount of railway carriages with dangerous cargo</b></label>
                <input asp-for="DC" class="form-control" />
                <span asp-validation-for="DC" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="w-12 btn-group" role="group">
            <a asp-action="Index" class="btn btn-info mx-1">🡸 Back</a>
            <input type="submit" class="btn btn-danger mx-1" value="✓ Save" />
        </div>
    </div>
</form>

TrainManagement.Web/Views/User/Login.cshtml
@model UserModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_LayoutUser";
    ViewData["Title"] = "Login";
}

<div>
    <div class="row pt-4">
        <div class="col-3">
            <h3>Login form</h3>
        </div>
        <div class="col-3">
            <a asp-controller="User" asp-action="Registration" class="btn btn-success mx-1">✓ Sign up</a>
        </div>
    </div>
</div>
<br />

<form method="post" asp-action="Login" autocomplete="off">
    <div class="container align-content-center">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <p><b>@ViewBag.LoginStatus</b></p>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" type="password"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="w-12 btn-group" role="group">
            <a asp-controller="Home" asp-action="Index" class="btn btn-info mx-1">🡸 Run app without registration</a>
            <input type="submit" class="btn btn-success mx-1" value="✓ Sign in" />
        </div>
    </div>
</form>

TrainManagement.Web/Views/User/Registration.cshtml
@model UserModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_LayoutUser";
    ViewData["Title"] = "Registration";
}

<div>
    <div class="row pt-4 pb-5">
        <div class="col-4">
            <h3>Registration form</h3>
        </div>
       @* <div class="col-3">
            <a asp-controller="User" asp-action="Registration" class="btn btn-success mx-1">Sign up</a>
        </div>*@
    </div>
</div>
<br />

<form method="post" asp-action="Registration" autocomplete="off">
    <div class="container align-content-center">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="col-4">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="w-12 btn-group" role="group">
            <a asp-controller="User" asp-action="Login" class="btn btn-info mx-1">🡸 Cancel</a>
            <input type="submit" class="btn btn-success mx-1" value="✓ Register" />
        </div>
    </div>
</form>